name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          plugin_languages: yes
          plugin_languages_ignored: html, css                           # List of languages to ignore
          plugin_la nguages_threshold: 2%                               # Hides all languages less than 2%
          plugin_languages_limit: 8                                     # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used           # Display most used and recently used languages stats
          plugin_languages_recent_load: 500                             # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 30                               # Limit recently used stats to last week
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_contributors: yes
          plugin_contributors_base: ""           # Base reference (commit, tag, branch, etc.)
          plugin_contributors_head: master       # Head reference (commit, tag, branch, etc.)
          plugin_contributors_ignored: bot       # Ignore "bot" user
          plugin_contributors_contributions: yes # Display number of contributions for each contributor
    
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
